use GTCongTy_db

CREATE TABLE PhanQuyen
(IdPhanQuyen INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TenPhanQuyen NVARCHAR(50) NOT NULL);

CREATE TABLE QuanTri
(TenDangNhap NVARCHAR(50) PRIMARY KEY NOT NULL,
MatKhau NVARCHAR(50) NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,
SDT NVARCHAR(50) NOT NULL,
IdPhanQuyen INT IDENTITY(1,1) FOREIGN KEY (IdPhanQuyen) REFERENCES PhanQuyen(IdPhanQuyen));

CREATE TABLE NguoiDung
(
TaiKhoan NVARCHAR(100) PRIMARY KEY NOT NULL,
MatKhau NVARCHAR(50) NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
Email NVARCHAR(100) NOT NULL,
NgayDangKy DATETIME NOT NULL,
TrangThai INT NOT NULL);

CREATE TABLE NhaPhanPhoiVaThuongHieu
(IDNSX INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TenNSX NVARCHAR(200) NOT NULL,
DiaChi NVARCHAR(max) NOT NULL,
SDT NVARCHAR(50) NOT NULL);

CREATE TABLE PhanLoai
(IdPhanLoai INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TenPhanLoai NVARCHAR(100) NOT NULL);

CREATE TABLE ThongTinSanPham
(IdSanPham INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TenSanPham NVARCHAR(200) NOT NULL,
IdNSX INT FOREIGN KEY (IdNSX) REFERENCES NhaPhanPhoiVaThuongHieu(IdNSX),
MoTa NVARCHAR(max) NOT NULL,
IdPhanLoai INT FOREIGN KEY (IdPhanLoai) REFERENCES PhanLoai(IdPhanLoai),
HinhAnh NVARCHAR(200) NOT NULL,
Gia MONEY NOT NULL,
SPMoi INT NOT NULL,
SPNoiBat INT NOT NULL);

CREATE TABLE BangTin
(IdBangTin INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TieuDe NVARCHAR(200) NOT NULL,
TenNguoiDang NVARCHAR(50) NOT NULL,
HinhAnh NVARCHAR(200) NOT NULL,
MoTa NVARCHAR(max) NOT NULL,
NgayDang DATETIME NOT NULL,
TrangThai INT NOT NULL,
IdSanPham INT FOREIGN KEY (IdSanPham) REFERENCES ThongTinSanPham(IdSanPham),
LuotXem BIGINT NOT NULL);

CREATE TABLE PhanHoi
(IdPhanHoi INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TieuDe NVARCHAR(100) NOT NULL,
NgayDang DATETIME NOT NULL,
IdBangTin INT FOREIGN KEY (IdBangTin) REFERENCES BangTin(IdBangTin),
TaiKhoan NVARCHAR(100) FOREIGN KEY (taiKhoan) REFERENCES NguoiDung(TaiKhoan));
