#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webgioithieu.App_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GTCongTy_db")]
	public partial class ConnectdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangTin(BangTin instance);
    partial void UpdateBangTin(BangTin instance);
    partial void DeleteBangTin(BangTin instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhaPhanPhoiVaThuongHieu(NhaPhanPhoiVaThuongHieu instance);
    partial void UpdateNhaPhanPhoiVaThuongHieu(NhaPhanPhoiVaThuongHieu instance);
    partial void DeleteNhaPhanPhoiVaThuongHieu(NhaPhanPhoiVaThuongHieu instance);
    partial void InsertPhanHoi(PhanHoi instance);
    partial void UpdatePhanHoi(PhanHoi instance);
    partial void DeletePhanHoi(PhanHoi instance);
    partial void InsertPhanLoai(PhanLoai instance);
    partial void UpdatePhanLoai(PhanLoai instance);
    partial void DeletePhanLoai(PhanLoai instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    partial void InsertQuanTri(QuanTri instance);
    partial void UpdateQuanTri(QuanTri instance);
    partial void DeleteQuanTri(QuanTri instance);
    partial void InsertThongTinSanPham(ThongTinSanPham instance);
    partial void UpdateThongTinSanPham(ThongTinSanPham instance);
    partial void DeleteThongTinSanPham(ThongTinSanPham instance);
    #endregion
		
		public ConnectdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GTCongTy_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangTin> BangTins
		{
			get
			{
				return this.GetTable<BangTin>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NhaPhanPhoiVaThuongHieu> NhaPhanPhoiVaThuongHieus
		{
			get
			{
				return this.GetTable<NhaPhanPhoiVaThuongHieu>();
			}
		}
		
		public System.Data.Linq.Table<PhanHoi> PhanHois
		{
			get
			{
				return this.GetTable<PhanHoi>();
			}
		}
		
		public System.Data.Linq.Table<PhanLoai> PhanLoais
		{
			get
			{
				return this.GetTable<PhanLoai>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<QuanTri> QuanTris
		{
			get
			{
				return this.GetTable<QuanTri>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinSanPham> ThongTinSanPhams
		{
			get
			{
				return this.GetTable<ThongTinSanPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangTin")]
	public partial class BangTin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdBangTin;
		
		private string _TieuDe;
		
		private string _TenNguoiDang;
		
		private string _HinhAnh;
		
		private string _MoTa;
		
		private System.DateTime _NgayDang;
		
		private int _TrangThai;
		
		private System.Nullable<int> _IdSanPham;
		
		private long _LuotXem;
		
		private EntitySet<PhanHoi> _PhanHois;
		
		private EntityRef<ThongTinSanPham> _ThongTinSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBangTinChanging(int value);
    partial void OnIdBangTinChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTenNguoiDangChanging(string value);
    partial void OnTenNguoiDangChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNgayDangChanging(System.DateTime value);
    partial void OnNgayDangChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    partial void OnIdSanPhamChanging(System.Nullable<int> value);
    partial void OnIdSanPhamChanged();
    partial void OnLuotXemChanging(long value);
    partial void OnLuotXemChanged();
    #endregion
		
		public BangTin()
		{
			this._PhanHois = new EntitySet<PhanHoi>(new Action<PhanHoi>(this.attach_PhanHois), new Action<PhanHoi>(this.detach_PhanHois));
			this._ThongTinSanPham = default(EntityRef<ThongTinSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBangTin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdBangTin
		{
			get
			{
				return this._IdBangTin;
			}
			set
			{
				if ((this._IdBangTin != value))
				{
					this.OnIdBangTinChanging(value);
					this.SendPropertyChanging();
					this._IdBangTin = value;
					this.SendPropertyChanged("IdBangTin");
					this.OnIdBangTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNguoiDang
		{
			get
			{
				return this._TenNguoiDang;
			}
			set
			{
				if ((this._TenNguoiDang != value))
				{
					this.OnTenNguoiDangChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDang = value;
					this.SendPropertyChanged("TenNguoiDang");
					this.OnTenNguoiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSanPham", DbType="Int")]
		public System.Nullable<int> IdSanPham
		{
			get
			{
				return this._IdSanPham;
			}
			set
			{
				if ((this._IdSanPham != value))
				{
					if (this._ThongTinSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdSanPham = value;
					this.SendPropertyChanged("IdSanPham");
					this.OnIdSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="BigInt NOT NULL")]
		public long LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangTin_PhanHoi", Storage="_PhanHois", ThisKey="IdBangTin", OtherKey="IdBangTin")]
		public EntitySet<PhanHoi> PhanHois
		{
			get
			{
				return this._PhanHois;
			}
			set
			{
				this._PhanHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinSanPham_BangTin", Storage="_ThongTinSanPham", ThisKey="IdSanPham", OtherKey="IdSanPham", IsForeignKey=true)]
		public ThongTinSanPham ThongTinSanPham
		{
			get
			{
				return this._ThongTinSanPham.Entity;
			}
			set
			{
				ThongTinSanPham previousValue = this._ThongTinSanPham.Entity;
				if (((previousValue != value) 
							|| (this._ThongTinSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTinSanPham.Entity = null;
						previousValue.BangTins.Remove(this);
					}
					this._ThongTinSanPham.Entity = value;
					if ((value != null))
					{
						value.BangTins.Add(this);
						this._IdSanPham = value.IdSanPham;
					}
					else
					{
						this._IdSanPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThongTinSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanHois(PhanHoi entity)
		{
			this.SendPropertyChanging();
			entity.BangTin = this;
		}
		
		private void detach_PhanHois(PhanHoi entity)
		{
			this.SendPropertyChanging();
			entity.BangTin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private System.DateTime _NgayDangKy;
		
		private int _TrangThai;
		
		private EntitySet<PhanHoi> _PhanHois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayDangKyChanging(System.DateTime value);
    partial void OnNgayDangKyChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public NguoiDung()
		{
			this._PhanHois = new EntitySet<PhanHoi>(new Action<PhanHoi>(this.attach_PhanHois), new Action<PhanHoi>(this.detach_PhanHois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_PhanHoi", Storage="_PhanHois", ThisKey="TaiKhoan", OtherKey="TaiKhoan")]
		public EntitySet<PhanHoi> PhanHois
		{
			get
			{
				return this._PhanHois;
			}
			set
			{
				this._PhanHois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanHois(PhanHoi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_PhanHois(PhanHoi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaPhanPhoiVaThuongHieu")]
	public partial class NhaPhanPhoiVaThuongHieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNSX;
		
		private string _TenNSX;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<ThongTinSanPham> _ThongTinSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNSXChanging(int value);
    partial void OnIDNSXChanged();
    partial void OnTenNSXChanging(string value);
    partial void OnTenNSXChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NhaPhanPhoiVaThuongHieu()
		{
			this._ThongTinSanPhams = new EntitySet<ThongTinSanPham>(new Action<ThongTinSanPham>(this.attach_ThongTinSanPhams), new Action<ThongTinSanPham>(this.detach_ThongTinSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNSX", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNSX
		{
			get
			{
				return this._IDNSX;
			}
			set
			{
				if ((this._IDNSX != value))
				{
					this.OnIDNSXChanging(value);
					this.SendPropertyChanging();
					this._IDNSX = value;
					this.SendPropertyChanged("IDNSX");
					this.OnIDNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSX", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenNSX
		{
			get
			{
				return this._TenNSX;
			}
			set
			{
				if ((this._TenNSX != value))
				{
					this.OnTenNSXChanging(value);
					this.SendPropertyChanging();
					this._TenNSX = value;
					this.SendPropertyChanged("TenNSX");
					this.OnTenNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoiVaThuongHieu_ThongTinSanPham", Storage="_ThongTinSanPhams", ThisKey="IDNSX", OtherKey="IdNSX")]
		public EntitySet<ThongTinSanPham> ThongTinSanPhams
		{
			get
			{
				return this._ThongTinSanPhams;
			}
			set
			{
				this._ThongTinSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinSanPhams(ThongTinSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoiVaThuongHieu = this;
		}
		
		private void detach_ThongTinSanPhams(ThongTinSanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoiVaThuongHieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanHoi")]
	public partial class PhanHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhanHoi;
		
		private string _TieuDe;
		
		private System.DateTime _NgayDang;
		
		private System.Nullable<int> _IdBangTin;
		
		private string _TaiKhoan;
		
		private EntityRef<BangTin> _BangTin;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhanHoiChanging(int value);
    partial void OnIdPhanHoiChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNgayDangChanging(System.DateTime value);
    partial void OnNgayDangChanged();
    partial void OnIdBangTinChanging(System.Nullable<int> value);
    partial void OnIdBangTinChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    #endregion
		
		public PhanHoi()
		{
			this._BangTin = default(EntityRef<BangTin>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhanHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPhanHoi
		{
			get
			{
				return this._IdPhanHoi;
			}
			set
			{
				if ((this._IdPhanHoi != value))
				{
					this.OnIdPhanHoiChanging(value);
					this.SendPropertyChanging();
					this._IdPhanHoi = value;
					this.SendPropertyChanged("IdPhanHoi");
					this.OnIdPhanHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBangTin", DbType="Int")]
		public System.Nullable<int> IdBangTin
		{
			get
			{
				return this._IdBangTin;
			}
			set
			{
				if ((this._IdBangTin != value))
				{
					if (this._BangTin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdBangTinChanging(value);
					this.SendPropertyChanging();
					this._IdBangTin = value;
					this.SendPropertyChanged("IdBangTin");
					this.OnIdBangTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(100)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangTin_PhanHoi", Storage="_BangTin", ThisKey="IdBangTin", OtherKey="IdBangTin", IsForeignKey=true)]
		public BangTin BangTin
		{
			get
			{
				return this._BangTin.Entity;
			}
			set
			{
				BangTin previousValue = this._BangTin.Entity;
				if (((previousValue != value) 
							|| (this._BangTin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangTin.Entity = null;
						previousValue.PhanHois.Remove(this);
					}
					this._BangTin.Entity = value;
					if ((value != null))
					{
						value.PhanHois.Add(this);
						this._IdBangTin = value.IdBangTin;
					}
					else
					{
						this._IdBangTin = default(Nullable<int>);
					}
					this.SendPropertyChanged("BangTin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_PhanHoi", Storage="_NguoiDung", ThisKey="TaiKhoan", OtherKey="TaiKhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.PhanHois.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.PhanHois.Add(this);
						this._TaiKhoan = value.TaiKhoan;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanLoai")]
	public partial class PhanLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhanLoai;
		
		private string _TenPhanLoai;
		
		private EntitySet<ThongTinSanPham> _ThongTinSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhanLoaiChanging(int value);
    partial void OnIdPhanLoaiChanged();
    partial void OnTenPhanLoaiChanging(string value);
    partial void OnTenPhanLoaiChanged();
    #endregion
		
		public PhanLoai()
		{
			this._ThongTinSanPhams = new EntitySet<ThongTinSanPham>(new Action<ThongTinSanPham>(this.attach_ThongTinSanPhams), new Action<ThongTinSanPham>(this.detach_ThongTinSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhanLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPhanLoai
		{
			get
			{
				return this._IdPhanLoai;
			}
			set
			{
				if ((this._IdPhanLoai != value))
				{
					this.OnIdPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._IdPhanLoai = value;
					this.SendPropertyChanged("IdPhanLoai");
					this.OnIdPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenPhanLoai
		{
			get
			{
				return this._TenPhanLoai;
			}
			set
			{
				if ((this._TenPhanLoai != value))
				{
					this.OnTenPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenPhanLoai = value;
					this.SendPropertyChanged("TenPhanLoai");
					this.OnTenPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoai_ThongTinSanPham", Storage="_ThongTinSanPhams", ThisKey="IdPhanLoai", OtherKey="IdPhanLoai")]
		public EntitySet<ThongTinSanPham> ThongTinSanPhams
		{
			get
			{
				return this._ThongTinSanPhams;
			}
			set
			{
				this._ThongTinSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinSanPhams(ThongTinSanPham entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoai = this;
		}
		
		private void detach_ThongTinSanPhams(ThongTinSanPham entity)
		{
			this.SendPropertyChanging();
			entity.PhanLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhanQuyen;
		
		private string _TenPhanQuyen;
		
		private EntitySet<QuanTri> _QuanTris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhanQuyenChanging(int value);
    partial void OnIdPhanQuyenChanged();
    partial void OnTenPhanQuyenChanging(string value);
    partial void OnTenPhanQuyenChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._QuanTris = new EntitySet<QuanTri>(new Action<QuanTri>(this.attach_QuanTris), new Action<QuanTri>(this.detach_QuanTris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhanQuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPhanQuyen
		{
			get
			{
				return this._IdPhanQuyen;
			}
			set
			{
				if ((this._IdPhanQuyen != value))
				{
					this.OnIdPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._IdPhanQuyen = value;
					this.SendPropertyChanged("IdPhanQuyen");
					this.OnIdPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanQuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPhanQuyen
		{
			get
			{
				return this._TenPhanQuyen;
			}
			set
			{
				if ((this._TenPhanQuyen != value))
				{
					this.OnTenPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenPhanQuyen = value;
					this.SendPropertyChanged("TenPhanQuyen");
					this.OnTenPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_QuanTri", Storage="_QuanTris", ThisKey="IdPhanQuyen", OtherKey="IdPhanQuyen")]
		public EntitySet<QuanTri> QuanTris
		{
			get
			{
				return this._QuanTris;
			}
			set
			{
				this._QuanTris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuanTris(QuanTri entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_QuanTris(QuanTri entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanTri")]
	public partial class QuanTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _SDT;
		
		private int _IdPhanQuyen;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnIdPhanQuyenChanging(int value);
    partial void OnIdPhanQuyenChanged();
    #endregion
		
		public QuanTri()
		{
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhanQuyen", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IdPhanQuyen
		{
			get
			{
				return this._IdPhanQuyen;
			}
			set
			{
				if ((this._IdPhanQuyen != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._IdPhanQuyen = value;
					this.SendPropertyChanged("IdPhanQuyen");
					this.OnIdPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_QuanTri", Storage="_PhanQuyen", ThisKey="IdPhanQuyen", OtherKey="IdPhanQuyen", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.QuanTris.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.QuanTris.Add(this);
						this._IdPhanQuyen = value.IdPhanQuyen;
					}
					else
					{
						this._IdPhanQuyen = default(int);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinSanPham")]
	public partial class ThongTinSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSanPham;
		
		private string _TenSanPham;
		
		private System.Nullable<int> _IdNSX;
		
		private string _MoTa;
		
		private System.Nullable<int> _IdPhanLoai;
		
		private string _HinhAnh;
		
		private decimal _Gia;
		
		private int _SPMoi;
		
		private int _SPNoiBat;
		
		private EntitySet<BangTin> _BangTins;
		
		private EntityRef<NhaPhanPhoiVaThuongHieu> _NhaPhanPhoiVaThuongHieu;
		
		private EntityRef<PhanLoai> _PhanLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSanPhamChanging(int value);
    partial void OnIdSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnIdNSXChanging(System.Nullable<int> value);
    partial void OnIdNSXChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnIdPhanLoaiChanging(System.Nullable<int> value);
    partial void OnIdPhanLoaiChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    partial void OnSPMoiChanging(int value);
    partial void OnSPMoiChanged();
    partial void OnSPNoiBatChanging(int value);
    partial void OnSPNoiBatChanged();
    #endregion
		
		public ThongTinSanPham()
		{
			this._BangTins = new EntitySet<BangTin>(new Action<BangTin>(this.attach_BangTins), new Action<BangTin>(this.detach_BangTins));
			this._NhaPhanPhoiVaThuongHieu = default(EntityRef<NhaPhanPhoiVaThuongHieu>);
			this._PhanLoai = default(EntityRef<PhanLoai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSanPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSanPham
		{
			get
			{
				return this._IdSanPham;
			}
			set
			{
				if ((this._IdSanPham != value))
				{
					this.OnIdSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdSanPham = value;
					this.SendPropertyChanged("IdSanPham");
					this.OnIdSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNSX", DbType="Int")]
		public System.Nullable<int> IdNSX
		{
			get
			{
				return this._IdNSX;
			}
			set
			{
				if ((this._IdNSX != value))
				{
					if (this._NhaPhanPhoiVaThuongHieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNSXChanging(value);
					this.SendPropertyChanging();
					this._IdNSX = value;
					this.SendPropertyChanged("IdNSX");
					this.OnIdNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhanLoai", DbType="Int")]
		public System.Nullable<int> IdPhanLoai
		{
			get
			{
				return this._IdPhanLoai;
			}
			set
			{
				if ((this._IdPhanLoai != value))
				{
					if (this._PhanLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._IdPhanLoai = value;
					this.SendPropertyChanged("IdPhanLoai");
					this.OnIdPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPMoi", DbType="Int NOT NULL")]
		public int SPMoi
		{
			get
			{
				return this._SPMoi;
			}
			set
			{
				if ((this._SPMoi != value))
				{
					this.OnSPMoiChanging(value);
					this.SendPropertyChanging();
					this._SPMoi = value;
					this.SendPropertyChanged("SPMoi");
					this.OnSPMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPNoiBat", DbType="Int NOT NULL")]
		public int SPNoiBat
		{
			get
			{
				return this._SPNoiBat;
			}
			set
			{
				if ((this._SPNoiBat != value))
				{
					this.OnSPNoiBatChanging(value);
					this.SendPropertyChanging();
					this._SPNoiBat = value;
					this.SendPropertyChanged("SPNoiBat");
					this.OnSPNoiBatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinSanPham_BangTin", Storage="_BangTins", ThisKey="IdSanPham", OtherKey="IdSanPham")]
		public EntitySet<BangTin> BangTins
		{
			get
			{
				return this._BangTins;
			}
			set
			{
				this._BangTins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoiVaThuongHieu_ThongTinSanPham", Storage="_NhaPhanPhoiVaThuongHieu", ThisKey="IdNSX", OtherKey="IDNSX", IsForeignKey=true)]
		public NhaPhanPhoiVaThuongHieu NhaPhanPhoiVaThuongHieu
		{
			get
			{
				return this._NhaPhanPhoiVaThuongHieu.Entity;
			}
			set
			{
				NhaPhanPhoiVaThuongHieu previousValue = this._NhaPhanPhoiVaThuongHieu.Entity;
				if (((previousValue != value) 
							|| (this._NhaPhanPhoiVaThuongHieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaPhanPhoiVaThuongHieu.Entity = null;
						previousValue.ThongTinSanPhams.Remove(this);
					}
					this._NhaPhanPhoiVaThuongHieu.Entity = value;
					if ((value != null))
					{
						value.ThongTinSanPhams.Add(this);
						this._IdNSX = value.IDNSX;
					}
					else
					{
						this._IdNSX = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaPhanPhoiVaThuongHieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanLoai_ThongTinSanPham", Storage="_PhanLoai", ThisKey="IdPhanLoai", OtherKey="IdPhanLoai", IsForeignKey=true)]
		public PhanLoai PhanLoai
		{
			get
			{
				return this._PhanLoai.Entity;
			}
			set
			{
				PhanLoai previousValue = this._PhanLoai.Entity;
				if (((previousValue != value) 
							|| (this._PhanLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanLoai.Entity = null;
						previousValue.ThongTinSanPhams.Remove(this);
					}
					this._PhanLoai.Entity = value;
					if ((value != null))
					{
						value.ThongTinSanPhams.Add(this);
						this._IdPhanLoai = value.IdPhanLoai;
					}
					else
					{
						this._IdPhanLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanLoai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangTins(BangTin entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinSanPham = this;
		}
		
		private void detach_BangTins(BangTin entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinSanPham = null;
		}
	}
}
#pragma warning restore 1591
